#!/bin/sh

# redirect stderr
exec 2>&1

export JAVA_HOME={{pkgPathFor "core/jre8"}}

dir_symlink_fix() {
	DSTDIR=$1
	SYMLINK=$2

	[ -d ${DSTDIR} ] || mkdir -p ${DSTDIR}
	[ -d ${SYMLINK} -a ! -L ${SYMLINK} ] && mv ${SYMLINK} `mktemp -u ${SYMLINK}.XXXXXXXX`
	[ "$(readlink ${SYMLINK})" = "${DSTDIR}" ] || (rm -f ${SYMLINK} && ln -sf ${DSTDIR} ${SYMLINK})
}

file_symlink_fix() {
	DSTFILE=$1
	SYMLINK=$2

	if [ -f ${DSTFILE} ]; then
		[ -f ${SYMLINK} -a ! -L ${SYMLINK} ] && mv ${SYMLINK} `mktemp -u ${SYMLINK}.XXXXXXXX`
		[ "$(readlink ${SYMLINK})" = "${DSTFILE}" ] || (rm -f ${SYMLINK} && ln -sf ${DSTFILE} ${SYMLINK})
	fi
}

for dir in bin conf lib webapps dl
do
	cp -r "{{pkg.path}}/$dir" "{{pkg.svc_static_path}}/$dir"
done

dir_symlink_fix "{{pkg.svc_data_path}}" "{{pkg.svc_static_path}}/data"
dir_symlink_fix "{{pkg.svc_path}}/logs" "{{pkg.svc_static_path}}/logs"
dir_symlink_fix "{{pkg.svc_var_path}}" "{{pkg.svc_static_path}}/run"

{{~#if cfg.unifi.ssl.keystore}}
  file_symlink_fix "{{cfg.unifi.ssl.keystore}}" "{{pkg.svc_data_path}}/keystore"
{{~/if}}

file_symlink_fix "{{pkgPathFor "core/mongodb"}}/bin/mongod" "{{pkg.svc_static_path}}/bin/mongod"

dir_symlink_fix "{{pkg.svc_data_path}}" "/data"

echo "unifi.config.readEnv=true" >> {{pkg.svc_data_path}}/system.properties
echo "unifi.logStdout=true" >> {{pkg.svc_data_path}}/system.properties
