#!/bin/sh

# redirect stderr
exec 2>&1

source {{pkg.svc_path}}/config/properties.sh

export JAVA_HOME={{pkgPathFor "core/jre8"}}

BASEDIR="{{pkg.svc_static_path}}"
DATADIR="{{pkg.svc_data_path}}"
LOGDIR="{{pkg.svc_path}}/logs"
RUNDIR="{{pkg.svc_var_path}}"
PIDFILE="${RUNDIR}/{{pkg.name}}.pid"
JSVCDIR={{pkgPathFor "cerny-cc/commons-daemon"}}
MAINCLASS="com.ubnt.ace.Launcher"

JVM_EXTRA_OPTS="${JVM_EXTRA_OPTS} -Dunifi.datadir=${DATADIR} -Dunifi.logdir=${LOGDIR} -Dunifi.rundir=${RUNDIR}"
{{~#each cfg.java}}
JVM_EXTRA_OPTS="${JVM_EXTRA_OPTS} -{{@key}}{{this}}"
{{~/each}}

JVM_OPTS="${JVM_EXTRA_OPTS} -Djava.awt.headless=true -Dfile.encoding=UTF-8"

JSVC="${JSVCDIR}/bin/jsvc"

JSVC_OPTS="${JSVC_OPTS}\
 -home ${JAVA_HOME} \
 -cwd {{pkg.svc_static_path}} \
 -cp ${JSVCDIR}/lib/commons-daemon.jar:${BASEDIR}/lib/ace.jar \
 -pidfile ${PIDFILE} \
 -procname {{pkg.name}} \
 -outfile SYSLOG \
 -errfile SYSLOG \
 -nodetach \
 ${JSVC_EXTRA_OPTS} \
 ${JVM_OPTS}"

exec ${JSVC} ${JSVC_OPTS} ${MAINCLASS} start
